name: Build PBR

on:
  schedule:
    #- cron: "2 0/1 * * *"
    - cron: "* * * * *"
  workflow_dispatch:

# 解决方案
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download cidr
      run: |
        chmod +x ros-dpbr.sh
        ./ros-dpbr.sh
        
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
